services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      PROMPTIC_DEBUG: ${PROMPTIC_DEBUG}
    volumes:
      - gradio_cache:/app/.gradio/gradio_cached_examples

volumes:
  gradio_cache:
