services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      PROMPTIC_DEBUG: ${PROMPTIC_DEBUG}
    volumes:
      - gradio:/app/.gradio

volumes:
  gradio:
